[package]
name = "voxels_java"
version = "0.2.13"
edition = "2021"

[lib]
name = "voxels_java"
crate-type = ["cdylib"]

[dependencies]
voxels_core = { path = "../core" }
robusta_jni = "0.2"
jni = "0.21"
flate2="1.1.9"
