[package]
name = "voxels_rs"
version = "0.1.13"
edition = "2021"

[lib]
name = "voxels_rs"
crate-type = ["cdylib"]

[dependencies]
voxels_core = { path = "../core" }
pyo3 = { version = "0.28.0", features = ["extension-module"] }
flate2 = "1.1.8"
numpy = "0.28.0"