[package]
name = "voxels_core"
version = "0.2.13"
edition = "2021"

[dependencies]
fastnbt = "2.6.0"
flate2="1.1.8"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
rand = "0.10.0-rc.9"
rand_chacha = "0.10.0"
rustc-hash = "2.1.1"
